### ISSUE TITLE
Spotify new API

### ISSUE THREAD

**Issue by guilhermesad** [philnash/meta-spotify#10]
Spotify has just launched a [new web API](https://developer.spotify.com/news-stories/2014/06/17/say-hello-new-web-api/) :grin:

**Comment by philnash** [comment]
Wow, so they have! And it looks like everything the Metadata API always should have been!

This probably calls for a deprecation notice, on this repo and in the gem, and a brand new gem to cover all the new stuff.

**Comment by guilhermesad** [comment]
Exactly. I've created a new gem trying to cover this new API: https://github.com/guilhermesad/rspotify
As you said, a lot has changed and I found it would be better to start from scratch, since even the repo "Metadata" name was deprecated. Any help would be very much appreciated! :)

**Comment by wrdhat** [comment]
Do you have a gem for rails 3?? 'cause rspotify need rails 4 and ruby 2

**Comment by philnash** [comment]
I'm afraid not, this gem is for an old version of the Spotify API. I'd recommend upgrading your Ruby and Rails if you don't support Ruby 2 yet, [Ruby 1.9.3 support ended a year ago](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/) and Ruby 2.0 is coming to an end too.
