### ISSUE TITLE
undefined method `artists' 

### ISSUE THREAD

**Issue by fionnbharra** [philnash/meta-spotify#5]
I've just installed your gem and am having trouble accessing any properties of the returned object. 

```
search = MetaSpotify::Artist.search('foo')  # this returns a hash
search.artists.first.name # undefined method `artists' for #<Hash:0x007fd37c6a3388>
```

I could be doing something wrong as I'm quite new to ruby.

**Comment by JackCA** [comment]
Vanilla Ruby hashes are not accessed that way. You'll need to use the `[key]` method on the hash e.g. `search[:artists]` in order to access that object.

**Comment by fionnbharra** [comment]
Thanks v much, I didn't realise that was required.
