### ISSUE TITLE
Connection refused using Metaspotify in a ruby backend

### ISSUE THREAD

**Issue by nmrtn** [philnash/meta-spotify#6]
1.9.3p194 :002 > MetaSpotify::Track.search('radiohead') Errno::ECONNREFUSED: Connection refused - connect(2)

any idea where does it come from ?

**Comment by philnash** [comment]
The Spotify API is down, it seems: http://ws.spotify.com/search/1/track?q=kaizers+orchestra

I will try to contact them to raise the issue.
